name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.x
          
      - name: Install Flutter dependencies
        run: flutter pub get
        
      - name: Analyze code
        run: flutter analyze || true
        
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./
          args: >
            -Dsonar.projectKey=my_flutter_app
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/generated/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}